version: "3.3"

services:

  front:
    #    image: sermalenk/skypro-front:version_1
    image: sermalenk/skypro-front:base
    ports:
      - '8002:80'
    depends_on:
      - api

  api:
    image: ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: b'django-insecure-qsib7!68w^zbce6)$jf3hyyul0f*j1do91$4gx)v@#bbcs+#7g'
      DEBUG: ${DEBUG}
    restart: always
    depends_on:
      - migrations
#          condition: service_completed_successfully

    command: python3 manage.py runserver 0.0.0.0:8000

  migrations:
    image: ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: b'django-insecure-qsib7!68w^zbce6)$jf3hyyul0f*j1do91$4gx)v@#bbcs+#7g'
      DEBUG: ${DEBUG}
    restart: always
    command: python manage.py migrate
