version: "3.9"

x-common-variables: &common-variables
  DB_PASSWORD: ${DB_PASSWORD}
  DB_USER: ${DB_USER}
  DB_NAME: ${DB_NAME}
  DB_HOST: postgres
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}

services:

  front:
#    image: sermalenk/skypro-front:version_1
#    image: sermalenk/skypro-front:base
    image: sermalenk/skypro-front:lesson_35
#    image: sermalenk/skypro-front:lesson_36
    ports:
      - '8080:80'
      - '8000:8000'
