version: "3.9"

services:

#  migrations:
#    build:
#      context: .
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_HOST: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#    command: python3 manage.py migrate

#  fixtures:
#    build:
#      context: .
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_HOST: postgres
#    depends_on:
#      migrations:
#        condition: service_completed_successfully
#    command: bash load_fixtures.sh

  front:
#    image: sermalenk/skypro-front:version_1
    image: sermalenk/skypro-front:base
    ports:
      - '8080:80'
    depends_on:
      - api

  api:
#    image: todolist
    build:
      context: .
    volumes:
      - .:/code
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
#    ports:
#      - "8080:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes:
#      - api_media:/opt/app/media

  migrations:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data/db/:/var/lib/postgresql/data

#volumes:
#  api_media: