version: "2.1"

services:

  front:
    image: sermalenk/skypro-front:lesson_38
    ports:
      - '8002:80'
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

  api:
    image: ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 'TRUE'
      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_HOST: redis
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/health/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    command: >
      sh -c "python3 manage.py migrate
            python3 manage.py runserver 0.0.0.0:8000"

  bot:
    image: ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 'TRUE'
      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_HOST: redis
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
    command: >
      sh -c "python3 manage.py migrate
            python3 manage.py runbot"

#  migrations:
#    image: ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    environment:
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_USER: ${DB_USER}
#      DB_NAME: ${DB_NAME}
#      DB_HOST: ${DB_HOST}
#      SECRET_KEY: ${SECRET_KEY}
#      DEBUG: 'TRUE'
#      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
#      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}
#      BOT_TOKEN: ${BOT_TOKEN}
#    depends_on:
#      postgres:
#        condition: service_healthy
#    command: >
#      sh -c "python3 manage.py migrate"

  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data/db/:/var/lib/postgresql/data
