# Generated by Django 4.0.3 on 2022-04-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
