# Generated by Django 4.0.3 on 2022-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
