version: '3.2'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_NAME=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
