name: "Build action"
on: [push]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: clone code
      uses: actions/checkout@v2
    - name: set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    - name: linting
      run: |
        flake8 core todolist --max-line-length=120
#    - name: run tests
#      run: |
#        coverage run --source=app -m pytest -v tests
#        coverage report --show-missing

#    - name: upload coverage to codecov
#      uses: codecov/codecov-action@v1

    - name: docker build
      run: docker build -t ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
    - name: docker login
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ipotemkin --password-stdin
    - name: docker push
      run: docker push ipotemkin/todolist_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
#      DB_HOST: postgres
#      DB_HOST: '127.0.0.1'
      DB_HOST: ${{ secrets.HOST }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: FALSE

    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-server.yaml | envsubst > deploy/docker-compose.yaml
#          cat prod_config.py | env_subst > deploy/docker_config.py
      - name: clone config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
#
##          TODO to change to token
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          source: "deploy/docker-compose.yaml"
          target: todolist
          strip_components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd todolist
            docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
